### ISSUE TITLE
Syntax collision with Type Ascription

### ISSUE THREAD

**Issue by hoodie** [phsym/prettytable-rs#11]
The current nightly of rustc merged [Type Ascription](https://github.com/rust-lang/rust/issues/23416), which seems to collide with the format syntax of prettytable-rs.

**Comment by phsym** [comment]
Do you think this is expected and I should change the macro syntax, or should I report this ?

**Comment by hoodie** [comment]
I have no idea. Though I suppose this might affect several crates. This issue already shows up as a mention in the linked RFC issue.

**Comment by phsym** [comment]
I also think it will affect several crates. Maybe I should wait a bit and see, or do you need an urgent fix ?

**Comment by hoodie** [comment]
Nope no biggy. I just wanted to mention this to you. Worst case: you have to change your api. Best case: the compiler learns to distinguish.
Let's see what happens.

**Comment by phsym** [comment]
By the way @hoodie, thank you for mentionning this issue. I don't play that mluch with nightly rust for now.

**Comment by daogangtang** [comment]
any new info？

**Comment by hoodie** [comment]
I would consider preemptively changing the macro syntax of _this_ crate. This could still be a valid 0.6.0 release.

**Comment by phsym** [comment]
That's also what I was thinking about. This won't be a big code change.

**Comment by phsym** [comment]
FYI, the crate has been fixed for nightly issue. I changed the macro syntax, and it's now available on crates.io in `v0.6.0`

**Comment by hoodie** [comment]
:+1:
*man do I wish github would just let me* **like** *your comment*

**Comment by phsym** [comment]
:smile: A thumb is all you need

**Comment by daogangtang** [comment]
:+1:
