### ISSUE TITLE
Allow skipping line separators

### ISSUE THREAD

**Issue by SOF3** [phsym/prettytable-rs#131]
It seems not possible to set a table format that does not print intern line separators.

**Comment by rickporter-tuono** [comment]
Just starting to use this, but I found FORMAT_NO_LINESEP_WITH_TITLE will skip the line separators. The example in the README.md works well. The one tweak I had to make to my code was use `table.set_titles()` instead of the `add_row()` for the header row.

**Comment by pinkforest** [comment]
Thanks for answering @rickporter-tuono
