### ISSUE TITLE
Mark crate as `deprecated` on crates.io

### ISSUE THREAD

**Issue by Nukesor** [phsym/prettytable-rs#139]
See #138 

This crate hasn't received a single commit or merged PR since about three years.
There also doesn't seem to be any intent of the crate author to continue working on this.

My proposal to @phsym is to mark this crate as deprecated so other people will think about using it twice.
I stumbled upon this library about two years ago myself and had to find out the hard way that it has been abandoned, after already spending a few hours working with it.
I guess it could be considered technical debt to use libraries that haven't received any updates since more than three years.

Furthermore, you should consider archiving this repository. Otherwise people will continue spending their time on PRs that'll never get merged.

This isn't intended to offend or blame anyone. Priorities shift all the time, there's no shame in leaving a project behind.
This is just a measure to keep the Rust ecosystem clean.

**Disclaimer:**

I wrote an alternative to this library, once I noticed that this project has been abandoned.
This PR is motivated by people asking me what the advantages of using either `prettytable-rs` or `comfy-table` are.

Pretty much all of those people weren't aware that this crate has been abandoned, which only shows that this is an ongoing problem that needs to be properly addressed.

**Comment by pinkforest** [comment]
This is maintained now, cutting out 1.0.0 today.
