### ISSUE TITLE
TableFormat documentation is outdated

### ISSUE THREAD

**Issue by matthiasbeyer** [phsym/prettytable-rs#14]
Hi,

the docs say that `TableFormat` gets a `Option<char>` as first parameter, but passing `None` results in:

```
src/ui/file.rs:165:45: 165:49 error: mismatched types:
expected `char`,
found `core::option::Option<_>`
```

Please fix. Besides, please continue contributing, I like your crate a lot!

**Comment by phsym** [comment]
Hi Matthias,
I see in your project that you are using `v0.4.0`. Current version is `v0.5.1`.
For now I only keep online (using Github pages) the doc for the latest published crate version.

**Comment by phsym** [comment]
I suggest you to switch to latest release, or if you want to keep `v0.4.0`, you can generate documentation by generating your crate's doc.

**Comment by matthiasbeyer** [comment]
Ah, sorry about that! I'll update my version, thanks!

**Comment by phsym** [comment]
No problem ;)
