### ISSUE TITLE
Replace atty dependency in prettytable-rs due to RUSTSEC-2021-0145

### ISSUE THREAD

**Issue by willbuckner** [phsym/prettytable-rs#144]
The title says it all, but there is an advisory for atty which is unmaintained, and this dependency likely needs to be replaced with something else. Advisory is here: https://rustsec.org/advisories/RUSTSEC-2021-0145.html

Thanks!

**Comment by pinkforest** [comment]
Yeah will get a PR for this one. There is also a panic #140 that needs to be checked.

**Comment by pinkforest** [comment]
Fixed via 0.10.0 Release
