### ISSUE TITLE
Running the compiled dirscan shows a segmentfault

### ISSUE THREAD

**Issue by fancity-xia** [phsym/prettytable-rs#163]
```rust
let tables = table!(["ABC", "DEFG", "HIJKLMN"],
                   ["foobar", "bar", "foo"],
                   ["foobar2", "bar2", "foo2"]);
tables.printstd(); 
// executed after compiled
Segmentation fault (core dumped)

// The problem is in the prettyable
table.printstd(); 
```
The above problem was encountered in the ec2 server of aws. 

Linux 3.10.0-1160.49.1.el7.x86_64  x86_64 x86_64 x86_64 GNU/Linux

**Comment by pinkforest** [comment]
I don't think this is problem in this crate ? There is not sufficient information to associate the segfault to this crate.

I think the problem is in something that just happens to use prettytable as there is no obvious cause-effect here.

Please provide [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) so if there is a problem it can be reproduced.

Re-open if this can be re-produced.

**Comment by fancity-xia** [comment]
Could it be a system compatibility issue？
I extracted the test data and tested it . 

`cargo 1.76.0 (c84b36747 2024-01-18)`

#### Cargo.toml
```toml
[dependencies]
prettytable-rs = "0.8.0"
```
#### main.rs
```rust

use prettytable::{cell, row};

#[macro_use] extern crate prettytable;
fn main() {
    let table2 = table!(["ABC", "DEFG", "HIJKLMN"],
                   ["foobar", "bar", "foo"],
                   ["foobar2", "bar2", "foo2"]);
    for row in table2.row_iter() {   // success
       println!("{:?}", row);   
    }
    table2.printstd();   // error 
}

```

**Comment by pinkforest** [comment]
Is there a particular reason 0.8 is used ?

```
[dependencies]
prettytable-rs = "0.8.0"
```
That is over five years old version and who knows what broken depency tree that might be pulling in along

Please could you try the latest version which is 0.10 ?

```
[dependencies]
prettytable-rs = "0.10"
```

Latest version can be always found from:
https://crates.io/crates/prettytable-rs

**Comment by fancity-xia** [comment]
Thank you for your reply,  I have solved the problem after upgrading .
