### ISSUE TITLE
Should I consider relicensing under dual MIT/Apache-2.0 ???

### ISSUE THREAD

**Issue by phsym** [phsym/prettytable-rs#17]
I got the following issue opened in another repository of mine phsym/sctp-sys#2.
It made me wondering if it would be a good idea to do it also for `prettytable-rs` in order to match better with rustlang licensing.

Any thought about that, someone ?

**Comment by Apanatshka** [comment]
It seems like a good idea to match the licensing scheme most of Rust and it's ecosystem uses. If you don't have any reservations again this licensing practice, why not :)

**Comment by phsym** [comment]
I'll probably change the license next time I do a major release
