### ISSUE TITLE
Improve documentation landing page

### ISSUE THREAD

**Issue by vessd** [phsym/prettytable-rs#20]
Documentation on the link in the README.md is broken

**Comment by phsym** [comment]
It works well for me. Could you detail a bit more your issue ?

**Comment by D101101** [comment]
![_2016-01-19_22-46-25](https://cloud.githubusercontent.com/assets/8783865/12430060/8645648a-befe-11e5-80e6-4966c38fa509.png)

**Comment by D101101** [comment]
Now I understand, it links to the different versions. Sorry, but it is not very obvious.

**Comment by phsym** [comment]
No problem. I made this recently and it needs to be improved. It's on my todo list

**Comment by phsym** [comment]
In a near future I'll probably rely on a service like [crates.fyi](https://crates.fyi/crates/prettytable-rs/) to store documentation, and only store doc for master branch on github-pages. Or maybe both solutions

**Comment by phsym** [comment]
And sorry for the long wait
