### ISSUE TITLE
Skip padding of final cell for FORMAT_CLEAN

### ISSUE THREAD

**Issue by keeperofdakeys** [phsym/prettytable-rs#22]
FORMAT_CLEAN doesn't technically require padding of the final cell, since each row has a newline at the end. This can be desirable to avoid ridiculous output when the final cell differs in width by hundreds of characters. I'm unsure if this would be preferable in all situations though.

**Comment by phsym** [comment]
Hi - You're totally right. The current implementation in fact define padding for all cells, and do not allow setting padding per cell, or neither it differeciate the first / last cell in a row from the other cell.

However, the current definition of `FORMAT_CLEAN` defines no column separator, with left and righ cell's padding set to 1.
This result in a cell printed like this `_value_` (where `_` represent a space) and the resulting row would be `_value__value__value_\n` with a minimum of 2 space between cells.

In fact, it may be indeed better to define `FORMAT_CLEAN` with no padding, a a space as column separator. The result would be a cell printed like `value` and a row printed `value_value_value\n`

This would remove extra space at the beginning and the end of the line, and reduce the minimum number of spaces between cells to only 1.

What do you think about that ?

**Comment by phsym** [comment]
You can of course manually define this kind of format with the following code :

```rust
use prettytable::format::FormatBuilder;

let my_clean_format = FormatBuilder::new()
         .column_separator(' ')
         .build();
table.set_format(my_clean_format);
```

**Comment by keeperofdakeys** [comment]
If I understand correctly, that code snippet won't fix the problem I'm describing. It's not the padding between cells that is the problem, but the padding within the cell. Here is a sample image: http://i.imgur.com/tNAAcSZ.png

As you can see, a single line of the table is taking up multiple lines due to the extra padding.

**Comment by phsym** [comment]
Oh ok I got it. You are talking about extra spaces added to fill the last cell in order to fit the last column width (based on the largest cell in that column), right ? I'm running out of time for tonight, but I'll get a look tomorrow

**Comment by keeperofdakeys** [comment]
Yes that's right, thanks for the prompt responses.

**Comment by keeperofdakeys** [comment]
Thanks, this fixes my issue.

**Comment by phsym** [comment]
Fixed published on crates.io in `v0.6.1`
