### ISSUE TITLE
Cell, row, column and table alignment

### ISSUE THREAD

**Issue by Firstyear** [phsym/prettytable-rs#25]
Hi,

I'm currently developing a tool (Process-Query) with @keeperofdakeys . I would like to be able to use your library to print text such as:

```bash
              total        used        free      shared  buff/cache   available
Mem:       12202880     3768524      663128      459220     7771228     7804748
```

Note that the first column is left aligned, and the rest are right aligned.

So I was thinking of various ways to implement alignment helpers beyond just per cell.

I don't think that alignment as part of the table format is correct. It would either override everything, be copied as cells are added, or have to be a "default". 

Each of these three has issues.

The override on everything, doesn't work in my case. You would need code that then allows Cell alignment to override table alignment. This adds complication.

Being copied as cells are added has it's own special issues. Consider (kinda pseudo code):

```rust
let mut table = Table::new();
table.add_row(vec![...]);
let format  =FormatBuilder::new().alignment(LEFT);
table.set_format(format);
```

This means the format can change part way through the tables construction, which could lead to nasty surprises.

Finally, having a default, would mean that cells would need to be able to express "default" alignment. So another type in the alignment enum. But this means you need code to again, check for the default vs a real alignment, collect the default from the format. You also need to make sure the format doesn't set the default enum value itself. More edge cases.

I think the perhaps the easiest solution is a collection of map functions. map row and map column. This would allow the application of a function to each cell in the table. This could be alignment, or some other formatting, so would be rather generic.

Alternately, an iter for mut row could be added to allow "for c in row" and "for c in column": Again, similar to map. 

What do you think? I'm happy to take your advice, and implement the solution. 

PS: Later this may apply to padding in each cell also, as I have some specific padding / width requirements I'd like to meet.

**Comment by phsym** [comment]
Hi,

You can already perform mutable and immutbale iterations over columns with [column_iter_mut](http://phsym.github.io/prettytable-rs/master/prettytable/struct.Table.html#method.column_iter_mut) and [column_iter](http://phsym.github.io/prettytable-rs/master/prettytable/struct.Table.html#method.column_iter) methods. But indeed, there is currently no way to get an iterator over rows.

When you say "a collection of map functions. map row and map column", do you mean, some functions/closures, stored into the `TableFormat`, which would be automatically applied to each row & columns before or during rendering ? Or each time a row is inserted or modified ?
Or do you mean helpers map functions the library users could call at any time before rendering the table ?

Something like
```rust
table.map_column(1, |ref mut cell| cell.align(Align::RIGHT));
```
and
```rust
table.get_mut_row(1).map(|ref mut cell| cell.align(Align::RIGHT));
// and / or
table.map_row(1, |ret mut cell| cell.align(Align::RIGHT));
```
?

**Comment by Firstyear** [comment]
Yeah, I mean the helpers. I was thinking something like 

```rust
table.get_mut_row(1).map(|ref mut cell| cell.align(Align::RIGHT));
table.get_mut_column(1).map(|ref mut cell| cell.align(Align::LEFT));
```
For example.

Is this something you would want in the library?

**Comment by phsym** [comment]
Sure that would be great indeed !

**Comment by phsym** [comment]
@Firstyear May I start working on this, or have you started something ? Or maybe you want to do it ?

**Comment by Firstyear** [comment]
I would like to do it, to learn more about rust, and to help you out. I've just been busy with work, but was hoping to look at this tonight / tomorrow.

**Comment by phsym** [comment]
No hurry, I leave it for you then.
