### ISSUE TITLE
Rename crate from 'prettytable-rs' to 'prettytable'

### ISSUE THREAD

**Issue by dtolnay** [phsym/prettytable-rs#32]
Every crate on crates.io is for Rust :smile: no reason for the -rs suffix.

**Comment by phsym** [comment]
I would have been agree until I discovered the Prettytable python library. Also, I'm note sure renaming a crate is possible on crates.io

**Comment by dtolnay** [comment]
I don't think renaming is possible but the next time you release a breaking change (0.7.0) you can publish it as prettytable instead of prettytable-rs.

**Comment by pzmarzly** [comment]
IMHO crate name should match repository name. If you rename crate, don't forget to rename the repo (Github will start redirecting all links).

If your crate target Rust devs only (and your do, as it's a library), feel free to drop `-rs`. If you want to be easier to find in Google, consider leaving it.

**Comment by vi** [comment]
This probably complicates experimenting with prettytable with [evcxr Rust REPL](https://github.com/google/evcxr/blob/master/evcxr_repl/README.md).

```
$ evcxr 
Welcome to evcxr. For help, type :help
>> extern crate prettytable;
error: no matching package named `prettytable` found
>> extern crate prettytable_rs;
error: no matching package named `prettytable_rs` found
>> :dep prettytable-rs = "*"
(waiting)
can't find crate for `prettytable_rs`
>> extern crate prettytable;
error: no matching package named `prettytable` found
```

**Comment by vi** [comment]
>  but the next time you release a breaking change (0.7.0) you can publish it as prettytable instead of prettytable-rs

Will version `0.9` be renamed?

**Comment by pinkforest** [comment]
There is 0.10 `prettytable` now as part of security release. Will continue to release to that as well.
