### ISSUE TITLE
Make platform specific newlines optional

### ISSUE THREAD

**Issue by Apanatshka** [phsym/prettytable-rs#33]
Right now this library [prints `\r\n` on windows](https://github.com/phsym/prettytable-rs/blob/master/src/utils.rs#L9-L12) for newlines. This makes my tool a bit inconsistent, because the rest of the tool doesn't special-case for windows. In general I don't think it's a big issue for command-line tools to output unix newlines since windows isn't a natural command-line platform. 

Can you add a way to turn off the platform specific newlines?

**Comment by phsym** [comment]
I'm agree windows is usually not used for command line tools, but it's still sometimes. I'd like the library to be compatible with windows CRLF end of lines. But I can define this to be a default feature which can be deactivated. Would that be ok for your use case ?

**Comment by Apanatshka** [comment]
A feature that can be deactivated would be great 👍

**Comment by phsym** [comment]
The fix landed in crate v0.6.3. Sorry I couldn't find some time to do that earlier.
By deactivating default features, there will be no windows secific line endings.

**Comment by Apanatshka** [comment]
Don't worry about the timing ;) It works great, thanks for adding this in!
