### ISSUE TITLE
Cell attributes won't show any change

### ISSUE THREAD

**Issue by sphinxc0re** [phsym/prettytable-rs#43]
I'm running a program on macOS. When using this section to put together a table:
```rust
for .. in .. {
    let mut index_cell = Cell::from(&index);
    index_cell.align(Alignment::RIGHT);

    let mut item_cell = Cell::from(&item.name);
    item_cell.style(Attr::ForegroundColor(0x00AAFF));
    table.add_row(row![index_cell, item.name, amount]);
}
```
the program compiles and runs but I neither see the alignment option working nor the color. Did I do something wrong?

**Comment by phsym** [comment]
Hi @sphinxc0re 
First, you are not adding `idem_cell` to the table, but `item.name` instead.
But even doing this won't be enough to display the colour correctly. In fact, you should not use the `row!` macro to create a new row from cells, since the macro will call `to_string()` on the cell in order to create a new cell. The macros are use to create tables/rows/cells from elements which can be converted to strings. Maybe I should consider refactoring this.
Heres what you should fo instead :
```rust
for .. in .. {
    let mut index_cell = Cell::from(&index);
    index_cell.align(Alignment::RIGHT);

    let mut item_cell = Cell::from(&item.name);
    item_cell.style(Attr::ForegroundColor(0x00AAFF));
    table.add_row(Row::new(vec![index_cell, item_cell, cell!(amount)]));
}
```

**Comment by phsym** [comment]
By the way, I'm not 100% sure you can use `0x00AAFF` as a foreground color. Sorry I can't check this right now.
This depends on the `term` crate and the colors should be one of [those](https://stebalien.github.io/doc/term/term/color/index.html).

**Comment by sphinxc0re** [comment]
Thank you for your fast response @phsym
I will try to refactor it as shown above

**Comment by phsym** [comment]
you're welcome

**Comment by phsym** [comment]
@sphinxc0re any update ?

**Comment by sphinxc0re** [comment]
@phsym I removed the dependency from my [project](https://github.com/raven-rpg/rpg-rs) entirely but only to make it a crate. When I write the first [implementation](https://github.com/raven-rpg/raven), I'll definitely reconsider using `prettytable-rs`

**Comment by phsym** [comment]
I'm closing issue for now. Feel free to reopen it later

**Comment by m4b** [comment]
So i'm not sure the best solution here, I noticed that the style spec isn't showing up for `name_cell` below, and I believe it's due to what you said above about `to_string` being called.

what would be the best way to mix and match style strings in the case below?

```rust
            let ph_name_table = |phdr: &elf::ProgramHeader| {
                let typ = phdr.p_type;
                let name = program_header::pt_to_str(typ);
                match typ {
                    program_header::PT_LOAD    => Cell::new(name).style_spec("Fr"),
                    program_header::PT_INTERP  => Cell::new(name).style_spec("Fy"),
                    program_header::PT_DYNAMIC => Cell::new(name).style_spec("Fc"),
                    _ =>  Cell::new(name),
                }
            };
            for (i, phdr) in phdrs.into_iter().enumerate() {
                let name_cell = ph_name_table(&phdr);
                let flags = ph_flag(&phdr);
                table.add_row(row![
                    format!("{} ", i),
                    name_cell,
                    format!("{:>4} ", flags),
                    Fy->format!("{:<#x} ", phdr.p_offset),
                    Fr->format!("{:<#x} ", phdr.p_vaddr),
                    bFr->format!("{:<#x} ", phdr.p_paddr),
                    Fg->format!("{:<#x} ", phdr.p_filesz),
                    bFg->format!("{:<#x} ", phdr.p_memsz),
                    format!("{:#x}", phdr.p_align)
                ]);
            }
            table.print_tty(self.opt.color);
```

**Comment by phsym** [comment]
Well, I would write
```rust
table.add_row(Row::new(vec![
                    cell!(format!("{} ", i)),
                    name_cell,
                    cell!(format!("{:>4} ", flags)),
                    cell!(Fy->format!("{:<#x} ", phdr.p_offset)),
                    cell!(Fr->format!("{:<#x} ", phdr.p_vaddr)),
                    cell!(bFr->format!("{:<#x} ", phdr.p_paddr)),
                    cell!(Fg->format!("{:<#x} ", phdr.p_filesz)),
                    cell!(bFg->format!("{:<#x} ", phdr.p_memsz)),
                    cell!(format!("{:#x}", phdr.p_align))
                ]));
```

I'm agree this could probably made better by adding other macros and / or refactoring the existing ones.

**Comment by phsym** [comment]
Maybe
```rust
cell!(Fy->format!("{:<#x} ", phdr.p_offset))
```
could be made into
```rust
format_cell!("Fy", "{:<#x} ", phdr.p_offset)
```
or maybe we could refacor the `cell!` macro so that
```rust
cell!(Fg -> "foobar")
```
could be written
```rust
cell!("Fg":"foobar")
```
(But need to find another symbol than `:`)
Then you could store the style string into a variable and pass it later during table contruction
