### ISSUE TITLE
No Column Separator

### ISSUE THREAD

**Issue by hoodie** [phsym/prettytable-rs#5]
Hi, is there a way to have NO column separator (for very tight tables), without changing the API?
Thanks

**Comment by phsym** [comment]
You can create a custom `format::TableFormat` with a column separator set to `' '` (space).
This won't remove the column separator, but simply replace it by a space character.
Don't forget to adapt line separators to replace '+' by `-` so a separator like `+----+----+` will become `-----------`

All this `TableFormat` API is a bit crappy for now and need to evolve to a much nicer API.

Allowing optional column separator is also possible as you suggested in pull request #6 .

**Comment by phsym** [comment]
v0.5.0 has just been published to crates.io. It contains the fix
