### ISSUE TITLE
Printing with indentation

### ISSUE THREAD

**Issue by hcpl** [phsym/prettytable-rs#51]
For example, this
```rust
let table = table!([["ABC", "DEFG", "HIJKLMN"],
                    ["foobar", "bar", "foo"],
                    ["foobar2", "bar2", "foo2"]]);

// there would be `_indented` counterparts for all printing methods if API shouldn't break
table.printstd();
table.printstd_indented(8);
```
renders
```
+---------+------+---------+
| ABC     | DEFG | HIJKLMN |
+---------+------+---------+
| foobar  | bar  | foo     |
+---------+------+---------+
| foobar2 | bar2 | foo2    |
+---------+------+---------+
        +---------+------+---------+
        | ABC     | DEFG | HIJKLMN |
        +---------+------+---------+
        | foobar  | bar  | foo     |
        +---------+------+---------+
        | foobar2 | bar2 | foo2    |
        +---------+------+---------+
```
Would this be implemented sometime?

P.S. For convenience, a few `table_print!`-like macros can be defined like
```rust
macro_rules! table_printstd {
    ($table:expr) => { $table.printstd() };
    ($table:expr, indent = $indent:expr) => { $table.printstd_indented($indent) };
}
/* define for other pairs of print methods */
```

**Comment by phsym** [comment]
What about setting indents into `TableFormat` instead ? This would avoid the need to have `*_indented` variant for every public functions performing some printing.

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hcpl** [comment]
Yes, formatting should be `TableFormat`'s area of responsibility.
And originally I even wanted something sophisticated as "place the table on 30% width position in the terminal"... This won't do with creating new set of functions, obviously :)

**Comment by phsym** [comment]
I'll get a look into this so it can land into `v0.6.7` too
