### ISSUE TITLE
Trailing comma results in infinite macro recursion

### ISSUE THREAD

**Issue by behnam** [phsym/prettytable-rs#68]
Looks like having a trailing comma in `row!()` invocation (and possibly other macros) results in infinite macro recursion.

I have something like this that triggers the error:
```rust
table.set_titles(row![
    Fg -> "Foo",
    Fg -> "Bar",
    "Baz",
    "Bad",
]);
```

**Comment by phsym** [comment]
Thanks for reporting it. Fix is in progress

**Comment by phsym** [comment]
Found it. It should work now. I'll release this in `0.6.8`
