### ISSUE TITLE
#[derive(Hash)] for Table, Row, Cell other user facing data types

### ISSUE THREAD

**Issue by rusterize** [phsym/prettytable-rs#73]
Thank you for sharing this crate, it is a great one!!

Could you please `#[derive(Hash)]` for the user facing data types? I want to put some tables in a `HashMap` and need the `Hash` trait.

It is always a good idea to implement the common traits listed in the [API Guidelines](https://rust-lang-nursery.github.io/api-guidelines/interoperability.html). I think you have most of them except `Hash``.

EDIT: These are the traits I use for data types, following the API guidelines:
`#[derive(Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug)]`

EDIT2: an impl of `std::iter::Extend` for Row (to add cells) and Table (to add rows) will also be important to follow the API guidelines. I need this one even more than the HashMap

**Comment by phsym** [comment]
I'll do this ASAP, then I'll get a deeper look to those guidelines

**Comment by phsym** [comment]
> I want to put some tables in a HashMap and need the Hash trait.
I guess you use tables as keys. If so, I also need to derive the `Eq` trait

**Comment by rusterize** [comment]
Thanks for your quick response, and for sharing and making this a great crate!

**Comment by phsym** [comment]
You're welcome

**Comment by phsym** [comment]
@rusterize Any comment on this PR ? Or shall I merge it ?

**Comment by phsym** [comment]
Merged. I'll publish that into `0.6.8` soon
