### ISSUE TITLE
Support box drawing characters

### ISSUE THREAD

**Issue by Emerentius** [phsym/prettytable-rs#83]
Unicode contains a set of characters to draw uninterrupted lines that can be used to create much cleaner, visually less noisy borders.
https://en.wikipedia.org/wiki/Box-drawing_character

Instead of
```
+---------+------+---------+
| ABC     | DEFG | HIJKLMN |
+---------+------+---------+
| foobar  | bar  | foo     |
+---------+------+---------+
| foobar2 | bar2 | foo2    |
+---------+------+---------+
```
you could create
```
┌─────────┬──────┬─────────┐
│ ABC     │ DEFG │ HIJKLMN │
├─────────┼──────┼─────────┤
│ foobar  │ bar  │ foo     │
├─────────┼──────┼─────────┤
│ foobar2 │ bar2 │ foo2    │
└─────────┴──────┴─────────┘
```
which is actually still interrupted vertically with the font my browser uses, but in my terminal and my editor those are connected.

Of course, legacy systems may not be able to deal with unicode, so you might want to keep it ASCII by default or at least add an ASCII fallback option.  
I'm not currently a user of the library, I just chanced upon it when I was searching for crates to help me add this functionality to tokei. It seems to from [the LineSeparator struct](https://docs.rs/prettytable-rs/0.7.0/prettytable/format/struct.LineSeparator.html) that the above table can't currently be created because there is only the distinction between junctions at the left and right border and the middle. Taking into account the top and bottom row, there are 5 junctions and 4 corners in total, not counting the half-bold, half-thin characters or half-single, half-double characters

**Comment by phsym** [comment]
Hi ! In fact it's possible. See [this test](https://github.com/phsym/prettytable-rs/blob/master/src/lib.rs#L936)

For sure it would probably fit in a predefined format
