### ISSUE TITLE
Improve / Refactor table format customization API

### ISSUE THREAD

**Issue by phsym** [phsym/prettytable-rs#9]
Table format customization API is a bit weird and not clean. Some refactoring should be done on it.
Builder Pattern may be use in a type named for example `FormatBuilder`.

What should be customizable :
- [x] Padding
    - [x] Right
    - [x] Left
- [x] Vertical separators
    - [x] Right
    - [x] Left
    - [x] Intern
- [x] Horizontal separators
    - [x] Top
    - [x] Bottom
    - [x] Intern
- [x] Junction characters
- [ ] ~~Colspan~~ (delayed to a next release)
- [ ] ~~Default style (alignment, colors , ...)~~ (delayed to a next release)
- [x] Implement builder pattern for API
- [x] Change default format constants to ~~functions or~~ `lazy_static` constants
- [x] Add a section about formatting in README
- [x] Add an example file

**Comment by hoodie** [comment]
Hi, just since you're openly thinking about it. It would be awesome if the api could allow different kinds of symbols for Top, Bottom and Intermittent separators, or colspans.
What do you think?

This could allow rendering something like this:

```bash
┌───────────────────────────────────────┐
│              test table               │
├───────────────────────────────────────┤
│         one  two  three   four   five │
├───────────────────────────────────────┤
│         one  two  three               │
│                3    4     5           │
│           2    3    4     5           │
│           3    3    5     605.0       │
│ hello world                           │
│          27                           │
│           1  two  three               │
└───────────────────────────────────────┘
```

**Comment by phsym** [comment]
:+1:  I'll take a look at this

**Comment by phsym** [comment]
**colspan** and **Default style** will be done later and added to a minor release
