### ISSUE TITLE
Update table in-place

### ISSUE THREAD

**Issue by gnzlbg** [phsym/prettytable-rs#90]
The tic-tac-toe example prints one table after the other. Would it be possible to have a "tic-tac-toe-inplace" example, where the table is updated in place ? How would I go about that ? 

I'm looking to use this to update a table in place that can grow (e.g. get more rows, so that columns get resized).

**Comment by phsym** [comment]
Hi! Would the following propositio  fit your need ?

Update the Table::print (and all it's friends, print_tty, print_std, and so on) to return the number of lines printed?

**Comment by gnzlbg** [comment]
Yes, currently I'm using `print_std`, so if that would return the number of lines printed, I can cache the result and use it the next time to move the cursor in the terminal and overwrite the previous table. 

I'm wondering, is there a function like `print_std`, but that lets me pass my own buffer ? I could also use something like that to print the table to a `String`, count the new lines, and then print the `String` to `stdout` or wherever I want.

**Comment by phsym** [comment]
You can use [print](http://phsym.github.io/prettytable-rs/master/prettytable/struct.Table.html#method.print), but you'll lose colors if you have some

**Comment by phsym** [comment]
@gnzlbg look at #92 

`pub fn printstd(&self) -> usize` will return the number of lines it has printed

**Comment by phsym** [comment]
Enhancement coming in release **v0.8.0**. Closing the issue
