### ISSUE TITLE
How to merge cells?

### ISSUE THREAD

**Issue by magj2006** [phsym/prettytable-rs#98]
Dear sir,
        I want to merge some cells, how to do it?

**Comment by phsym** [comment]
Hi, sorry for late reply. What do you mean exactly  by merging cells ?

**Comment by sanxiyn** [comment]
I think I can answer this because I had the same question. In HTML, you can use rowspan and colspan to merge cells. See https://html.com/tables/rowspan-colspan/ for examples.

**Comment by sanxiyn** [comment]
Note that colspan is already implemented: use `Cell::with_hspan`. rowspan is issue #29.

**Comment by magj2006** [comment]
@sanxiyn @phsym nice, thank you :)
