### ISSUE TITLE
Macros do not work with selective import

### ISSUE THREAD

**Issue by rotty** [phsym/prettytable-rs#99]
Since Rust 1.30, macros can be individually imported with [`use`](https://rust-lang-nursery.github.io/edition-guide/rust-2018/macros/macro-changes.html). This does not work for `ptable!`, `table!` and `row!`, as they invoke other macros, which must be imported as well, exposing what can be considered implementation details. For example, the following code produces errors in both `main` and `test_ptable`:

```rust
fn main() {
    use prettytable::row;
    row!["x"];
}

fn test_ptable() {
    use prettytable::ptable;
    ptable!(["A", "B", "C"]);
}
```

```
error: cannot find macro `cell!` in this scope                                                           
[...]
error: cannot find macro `table!` in this scope                                                          
```

If we can bump the Rust requirement to 1.30, the fix is quite straightforward, namely prefixing macro invocations with `$crate::`, see [the edition guide](https://rust-lang-nursery.github.io/edition-guide/rust-2018/macros/macro-changes.html#macros-with-crate-prefix). I'll submit a PR implementing this solution; unfortunatly, the solution (also explained in the edition guide) that works on older compilers as well is quite ugly IMO; I'll leave that as an exercise for the reader ;-).

**Comment by phsym** [comment]
Fixed by #100
